/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appexamenmatrices;

import java.util.Random;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author antares
 */
public class AppExamenMatriz extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AppExamenMatriz.class.getName());

    DefaultTableModel modeloTabla;
    DefaultTableModel modeloTablaPromSuc;
    DefaultTableModel modeloTablaPromMes;

    int[][] matriz;
    int[] promMes;
    int[] promSuc;

    public AppExamenMatriz() {
        initComponents();
        this.setLocationRelativeTo(null);
        modeloTabla = (DefaultTableModel) tPrincipal.getModel();

        modeloTablaPromSuc = (DefaultTableModel) tPromSuc.getModel();

        modeloTablaPromMes = (DefaultTableModel) tPromMes.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tPromMes = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tPromSuc = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tPrincipal = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tPromMes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "ENE", "FEB", "MAR", "ABR", "MAY", "JUN"
            }
        ));
        jScrollPane1.setViewportView(tPromMes);

        tPromSuc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Prom X suc"
            }
        ));
        jScrollPane2.setViewportView(tPromSuc);

        tPrincipal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ENE", "FEB", "MAR", "ABR", "MAY", "JUN"
            }
        ));
        jScrollPane3.setViewportView(tPrincipal);

        jButton1.setText("Llenar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jLabel1.setText("Prom xMes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Random rd = new Random();
        matriz = new int[modeloTabla.getRowCount()][modeloTabla.getColumnCount()];
        for (int i = 0; i < matriz.length; i++) {
            for (int j = 0; j < matriz[0].length; j++) {
                matriz[i][j] = rd.nextInt(50, 301);
            }
        }

        rellenar(matriz);

        for (int i = 0; i < modeloTablaPromSuc.getRowCount(); i++) {
            tPromSuc.setValueAt(promSuc[i], i, 0);
        }

        for (int i = 0; i < modeloTablaPromMes.getColumnCount(); i++) {
            tPromMes.setValueAt(promMes[i], 0, i);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    public void rellenar(int[][] relleno) {
        for (int i = 0; i < relleno.length; i++) {
            for (int j = 0; j < relleno[0].length; j++) {
                modeloTabla.setValueAt(relleno[i][j], i, j);
            }
        }
        
        mesSuc(relleno);
    }

    public void mesSuc(int[][] mat) {
        int filas = mat.length;
        int columnas = mat[0].length;

        promSuc = new int[filas];
        promMes = new int[columnas];

        for (int r = 0; r < filas; r++) {
            int sumaFila = 0;
            for (int c = 0; c < columnas; c++) {
                sumaFila += mat[r][c];
            }
            promSuc[r] = sumaFila / columnas;
        }

        for (int c = 0; c < columnas; c++) {
            int sumaCol = 0;
            for (int r = 0; r < filas; r++) {
                sumaCol += mat[r][c];
            }
            promMes[c] = sumaCol / filas;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AppExamenMatriz().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tPrincipal;
    private javax.swing.JTable tPromMes;
    private javax.swing.JTable tPromSuc;
    // End of variables declaration//GEN-END:variables
}
