
import java.util.Random;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author antares
 */
public class formaMatrix extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(formaMatrix.class.getName());

    /**
     * Creates new form formaMatrix
     */
    DefaultTableModel modeloTabla;
    DefaultTableModel modeloTablaVecNones;
    DefaultTableModel modeloTablaVecPares;
    
    int[][]matriz;
    int[]pares;
    int[]nones;
    

    public formaMatrix() {
        initComponents();
        this.setLocationRelativeTo(null);
        modeloTabla = (DefaultTableModel) tablaPrin.getModel();
        modeloTabla.setRowCount(Integer.parseInt(this.spinRengs.getValue().toString()));
        modeloTabla.setColumnCount(Integer.parseInt(this.spinCols.getValue().toString()));
        
        tablaPrin.setShowHorizontalLines(true);
        tablaPrin.setShowVerticalLines(true);
        
        modeloTablaVecNones = (DefaultTableModel) tablaNones.getModel();
        tablaNones.setShowHorizontalLines(true);
        modeloTablaVecNones.setRowCount(Integer.parseInt(this.spinRengs.getValue().toString()));
        
        modeloTablaVecPares = (DefaultTableModel) tablaPares.getModel();
        tablaPares.setShowVerticalLines(true);
        modeloTablaVecPares.setColumnCount(Integer.parseInt(this.spinCols.getValue().toString()));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgDatos = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        spinRengs = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        spinCols = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        rbDefault = new javax.swing.JRadioButton();
        rbCap = new javax.swing.JRadioButton();
        rbRandom = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaNones = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaPrin = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaPares = new javax.swing.JTable();
        btnDiagSec = new javax.swing.JButton();
        btnDiagPrin = new javax.swing.JButton();
        promDiagPrin = new javax.swing.JLabel();
        promDiagSec = new javax.swing.JLabel();
        btnPares = new javax.swing.JButton();
        btnNones = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("No.  Rengs:");

        spinRengs.setModel(new javax.swing.SpinnerNumberModel(3, 3, 5, 1));
        spinRengs.addChangeListener(this::spinRengsStateChanged);

        jLabel2.setText("No.  Cols:");

        spinCols.setModel(new javax.swing.SpinnerNumberModel(3, 3, 5, 1));
        spinCols.addChangeListener(this::spinColsStateChanged);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 0, 13), new java.awt.Color(0, 0, 0))); // NOI18N

        bgDatos.add(rbDefault);
        rbDefault.setText("X Default");
        rbDefault.addActionListener(this::rbDefaultActionPerformed);

        bgDatos.add(rbCap);
        rbCap.setText("Capturarlos");
        rbCap.addActionListener(this::rbCapActionPerformed);

        bgDatos.add(rbRandom);
        rbRandom.setText("Aleatorios");
        rbRandom.addActionListener(this::rbRandomActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbDefault)
                    .addComponent(rbCap)
                    .addComponent(rbRandom))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbDefault)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbCap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbRandom)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        tablaNones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nones"
            }
        ));
        jScrollPane1.setViewportView(tablaNones);

        tablaPrin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tablaPrin);

        tablaPares.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tablaPares);

        btnDiagSec.setText("Prom. Diag. Secundaria");
        btnDiagSec.addActionListener(this::btnDiagSecActionPerformed);

        btnDiagPrin.setText("Prom. Diag. Principal");
        btnDiagPrin.addActionListener(this::btnDiagPrinActionPerformed);

        promDiagPrin.setText("?");

        promDiagSec.setText("?");

        btnPares.setText("Det.Pares");
        btnPares.addActionListener(this::btnParesActionPerformed);

        btnNones.setText("Det. Nones");
        btnNones.addActionListener(this::btnNonesActionPerformed);

        jLabel3.setText("Alejandro Ortiz Talamantes 25130537");

        jLabel4.setText("Pares ->");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDiagSec)
                        .addGap(18, 18, 18)
                        .addComponent(promDiagSec)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(spinRengs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(spinCols, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDiagPrin)
                                .addGap(32, 32, 32)
                                .addComponent(promDiagPrin)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPares, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(spinRengs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(spinCols, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDiagPrin)
                            .addComponent(promDiagPrin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDiagSec)
                            .addComponent(promDiagSec)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNones)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPares)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCapActionPerformed
        for (int i = 0; i < matriz.length; i++) {
            for (int j = 0; j < matriz[0].length; j++) {
                modeloTabla.setValueAt("", i,j);
            }
        }
        tablaPrin.requestFocus();
    }//GEN-LAST:event_rbCapActionPerformed

    private void spinRengsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinRengsStateChanged
        modeloTabla.setRowCount(Integer.parseInt(this.spinRengs.getValue().toString()));
        modeloTablaVecNones.setRowCount(Integer.parseInt(this.spinRengs.getValue().toString()));
    }//GEN-LAST:event_spinRengsStateChanged

    private void spinColsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinColsStateChanged
        modeloTabla.setColumnCount(Integer.parseInt(this.spinCols.getValue().toString()));
        modeloTablaVecPares.setColumnCount(Integer.parseInt(this.spinCols.getValue().toString()));
    }//GEN-LAST:event_spinColsStateChanged

    private void btnDiagPrinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiagPrinActionPerformed
        int sum = 0;
        if (tablaPrin.getRowCount() == tablaPrin.getColumnCount()) {
            for (int i = 0, j = 0; i < matriz.length; i++, j++) {
                sum += matriz[i][j];
            }
            promDiagPrin.setText(String.format("%.2f", (double) sum / matriz.length));
        }
    }//GEN-LAST:event_btnDiagPrinActionPerformed

    private void rbDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDefaultActionPerformed
        spinRengs.setValue(3);
        spinCols.setValue(3);
        
        matriz = new int[][]{{1,2,3},{4,5,6},{7,8,9}};
        
        rellenar(matriz);
    }//GEN-LAST:event_rbDefaultActionPerformed

    private void rbRandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbRandomActionPerformed
        Random rd = new Random();
        matriz = new int [modeloTabla.getRowCount()][modeloTabla.getColumnCount()];
        for (int i = 0; i < matriz.length; i++) {
            for (int j = 0; j < matriz[0].length; j++) {
                matriz[i][j] = rd.nextInt(10,100);
            }
        }
        
        rellenar(matriz);
    }//GEN-LAST:event_rbRandomActionPerformed

    private void btnDiagSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiagSecActionPerformed
        int sum = 0;
        if (tablaPrin.getRowCount() == tablaPrin.getColumnCount()) {
            for (int i = 0, j = matriz.length - 1; j >= 0; i++, j--) {
                sum += matriz[i][j];
            }
            promDiagSec.setText(String.format("%.2f", (double) sum / matriz.length));
        }
    }//GEN-LAST:event_btnDiagSecActionPerformed

    private void btnNonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNonesActionPerformed
        for (int i = 0; i < tablaNones.getRowCount(); i++) {
            tablaNones.setValueAt(nones[i], i,0);
        }  
    }//GEN-LAST:event_btnNonesActionPerformed

    private void btnParesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParesActionPerformed
        for (int i = 0; i < tablaPares.getColumnCount(); i++) {
            tablaPares.setValueAt(pares[i], 0, i);
        }
    }//GEN-LAST:event_btnParesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new formaMatrix().setVisible(true));
    }
    
    public void rellenar(int [][] relleno){
        for (int i = 0; i < relleno.length; i++) {
            for (int j = 0; j < relleno[0].length; j++) {
                modeloTabla.setValueAt(relleno[i][j], i, j);
            }
        }
        paresNones(relleno);
    }
    
    public void paresNones(int[][] mat) {
        nones = new int[modeloTabla.getRowCount()];
        pares = new int[modeloTabla.getColumnCount()];

        for (int r = 0; r < mat.length; r++) {
            for (int c = 0; c < mat[0].length; c++) {
                if (mat[r][c] % 2 != 0) {
                    nones[r]++;
                } else {
                    pares[c]++;
                }
            }
        }
    }
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgDatos;
    private javax.swing.JButton btnDiagPrin;
    private javax.swing.JButton btnDiagSec;
    private javax.swing.JButton btnNones;
    private javax.swing.JButton btnPares;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel promDiagPrin;
    private javax.swing.JLabel promDiagSec;
    private javax.swing.JRadioButton rbCap;
    private javax.swing.JRadioButton rbDefault;
    private javax.swing.JRadioButton rbRandom;
    private javax.swing.JSpinner spinCols;
    private javax.swing.JSpinner spinRengs;
    private javax.swing.JTable tablaNones;
    private javax.swing.JTable tablaPares;
    private javax.swing.JTable tablaPrin;
    // End of variables declaration//GEN-END:variables
}
